name: company_field_app_flutter
description: "A comprehensive field management app - Fieldwire alternative"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  # UI & Navigation
  cupertino_icons: ^1.0.8
  
  # State Management & Navigation
  provider: ^6.1.2
  go_router: ^14.6.2
  
  # Database
  sqflite: ^2.4.1
  path_provider: ^2.1.5
  path: ^1.9.0
  
  # Camera & Images
  image_picker: ^1.1.2
  camera: ^0.11.0+2
  
  # Location
  geolocator: ^13.0.2
  permission_handler: ^11.3.1
  
  # File Management
  file_picker: ^8.1.4
  
  # PDF & Reports
  pdf: ^3.11.2
  printing: ^5.13.4
  
  # Utilities
  intl: ^0.20.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
